### ISSUE TITLE
pkr image purge conflicts with concurrent apps

### ISSUE THREAD

**Issue by nshimokochi** [altairengineering/pkr#44]
When two or more apps are deployed concurrently using pkr on the same Docker daemon, a pkr image purge (for one of the apps) may try to purge images used for currently running containers in the other app, resulting in an exception during the purge operation.

**Comment by Kimamisa** [comment]
Do you mean that you are deploying images the same application with the same tags name ? Because I had a look at this, and only images from the env referenced in the current Kard are targeted.

**Comment by redref** [comment]
Purge now has more flags to it adding more targetting to purged images.
