### ISSUE TITLE
pkr image purge removes only one copy of app images

### ISSUE THREAD

**Issue by nshimokochi** [altairengineering/pkr#45]
pkr renames pulled images to the host namespace; subsequently, a pkr image purge leaves behind the images having the original repo namespace, e.g. my-image:my-image-tag gets removed, but my-repo-namespace/my-image:my-image-tag remains.

**Comment by Kimamisa** [comment]
There is a parameter `repository` you can use when invoking purge:
pkr image purge -h
usage: pkr image purge [-h] [--tag TAG] [--except-tag EXCEPT_TAG] [--repository REPOSITORY]

optional arguments:
  -h, --help            show this help message and exit
  --tag TAG             Delete images with the given tag
  --except-tag EXCEPT_TAG
                        Do not delete images with the given tag
  --repository REPOSITORY
                        Delete image reference in a specified repository

Is this what is expected ?
